### ISSUE TITLE
Report Paste

### ISSUE THREAD

**Issue by kalarse** [felixphew/pokepaste#124]
I'd like to have a feature to report pastes if they show nicknames that are offensive.

**Comment by felixphew** [comment]
Hi @kalarse,

This is something that's been in and out of my mind ever since before PokePaste was even released on the world.

Broadly speaking, I think some process for handling problematic pastes might be advisable, but it's hard. Here are some of the difficulties that entails:
* How many reports would I get? I'm just one person, and there are 2.6 million pastes on PokePaste, with more than 50,000 added each week. (In practice, maybe the number of reports would be manageable, but I can't know that for sure, and putting in place a system and not acting on it is _not_ the kind of thing I'd want to do here.)
* Who decides what's offensive? Obviously, there's some things that are unambiguous, and maybe the case(s) that prompted you to open this issue are like that. But language is... really hard. Both meaning and connotations vary across cultural and national lines, some words that are used socially by the communities they describe are hurtful when used in other contexts, and don't forget that PokePaste goes beyond the English-speaking community - I don't have concrete stats, but there are sizeable numbers of Spanish and Japanese pastes, for example, and I speak neither language.
* What stops someone whose paste was removed from immediately making another? PokePaste doesn't require logins, so I have no effective ability to ban a person from the platform.

Remember PokePastes have to be shared somehow - they're not just a directory that people can browse. I feel like it'd be far more effective for the moderators or members of a group, a Discord server, a Pokemon Showdown chat, etc. to remove links _to_ an offending paste - they have access to the context in which it's being shared, larger communities will have organised moderators, and potentially structures in place to handle repeat offenders, all of which are lacking if I try to moderate centrally.

That said, please let me know what you think about this.

If this was sparked by a specific paste or pastes, and you don't think it'd be advisable to post the links here, then paste it with the nicknames removed, give me the link, and I should be able to pull the original out of the database.

**Comment by kalarse** [comment]
Hello,

First of all, I was unaware you were the sole worker on this project and
currently the only one working on it (maybe it was written somewhere and I
didn't get it), which I apologize since this "feature" request is probably
something you'd need a team alongside people you trust to make good
judgment.

What sparked this was a paste done in a small community that had a nickname
that sparked the current worldwide mood, which unfortunately was tied to a
Ghost type Pokémon, we have already spoke with this individual about this
and understood about the bad taste joke he wanted to make.

Here's the one without nicknames (https://pokepast.es/3e80301547944e4f)
probably you'll find 2 others cause I messed up while removing a nickname
and forgot to remove other.

I cannot thank enough the work you've put in order to make pokepast, since
it gives a better looking visual of backups without resorting to Pastebin
or a GDoc, and I apologize again if this request is something you've
received for thousand time, but as kinda moderator to a small community, we
can remove the link, but we don't have the power to avoid it being shared,
and personally I think it was a truly bad taste joke.

Thank you very much for taking the time to explain me the situation.

Please have a wonderful week.

Kind regards,

**Comment by felixphew** [comment]
Yep, I found the paste - and honestly, that's what I assumed it'd be given your description. It's especially tricky as it's not something easy like a slur, and is more a question of (potential) bad taste. And whether I think it'd be appropriate or not (I don't), I _definitely_ don't have the resources to be the taste police.

In the past, I have been willing to remove pastes by request from the person who made them, but (for privacy-related reasons) I no longer keep the logs necessary to validate someone's claim to be the author of a paste. I think I'm going to have to leave this up.

I wish you luck convincing this person that people might find that nickname insensitive or hurtful.

**Comment by kalarse** [comment]
I fully understand, no worries.

In the community we have already told him about the insensitive of that
nickname. I can only hope he understands.

I appreciate the time you took to answer me and let me know.

Again, I thank you for the wonderful work put in Pokepast!

Have a great day!
