### ISSUE TITLE
uu team

### ISSUE THREAD

**Issue by Luciano046** [felixphew/pokepaste#13]
Buzzwole @ Assault Vest  
Ability: Beast Boost  
EVs: 252 Atk / 252 SpD / 4 Spe  
Adamant Nature  
- Leech Life  
- Poison Jab  
- Hammer Arm  
- Ice Punch

Swampert @ Leftovers  
Ability: Torrent  
EVs: 252 HP / 4 Atk / 252 Def  
Impish Nature  
- Stealth Rock  
- Roar  
- Earthquake  
- Scald

Raikou @ Electrium Z  
Ability: Pressure  
EVs: 252 SpA / 4 SpD / 252 Spe  
Timid Nature  
- Calm Mind  
- Thunderbolt  
- Hidden Power [Ice]  
- Volt Switch

Scizor @ Choice Band  
Ability: Technician  
EVs: 252 Atk / 4 SpD / 252 Spe  
Adamant Nature  
- Bullet Punch  
- U-turn  
- Superpower  
- Pursuit

Primarina @ Choice Specs  
Ability: Torrent  
EVs: 4 Def / 252 SpA / 252 Spe  
Timid Nature  
IVs: 0 Atk  
- Hydro Pump  
- Moonblast  
- Energy Ball  
- Scald

Latias @ Soul Dew  
Ability: Levitate  
EVs: 252 SpA / 252 Spe  
Timid Nature  
IVs: 0 Atk  
- Psyshock  
- Draco Meteor  
- Calm Mind  
- Recover

**Comment by felixphew** [comment]
Hi there! I'm curious as to why you posted this here. This is a place to report issues or bugs with PokePaste itself. If you wanted to paste this team, go to http://pokepast.es and paste it in the large black text box. If something else is the issue, please don't hesitate to let me know, otherwise I'm closing this issue.
