### ISSUE TITLE
Help me finish team

### ISSUE THREAD

**Issue by EthanOfNote** [felixphew/pokepaste#23]

**Comment by felixphew** [comment]
Hi @EthanOfNote,

This issue tracker is designed for people to share issues and problems with PokePaste itself, not to ask for help with teambuilding. (Also, you haven't shared your team...)

If there's something wrong with the site that you'd like to report, please reply and let me know what it is. Otherwise, maybe try asking in [the RMT room on Pokemon Showdown](http://play.pokemonshowdown.com/rmt).
